# Generated by Django 3.0.7 on 2020-06-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200627_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='portfolio',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Портфолио'),
        ),
    ]
