# Generated by Django 3.0.7 on 2020-06-27 06:38

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200627_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('portfolio', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Портфолио')),
            ],
        ),
    ]
