# Generated by Django 3.0.7 on 2020-06-27 07:36

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(blank=True, max_length=2000, null=True, verbose_name='First text')),
                ('text2', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Second text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '360x430', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='portfolio',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Portfolio'),
        ),
    ]
