# Generated by Django 3.0.7 on 2020-06-27 10:10

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200627_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '340x410', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
