# Generated by Django 3.0.7 on 2020-06-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200627_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutread',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
