# Generated by Django 3.0.7 on 2020-07-15 11:42

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200715_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutread',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '669x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='aboutread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image'),
        ),
    ]
