# Generated by Django 3.0.7 on 2020-07-16 05:42

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200715_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Title')),
                ('text', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '460x220', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutread',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '900x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
