# Generated by Django 3.0.7 on 2020-07-17 08:42

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200716_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '900x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
    ]
