# Generated by Django 3.0.7 on 2020-07-20 12:17

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_advices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForPatientBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '430x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
